# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Goalish' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Goalish
  pod 'Firebase/Messaging'
  pod 'Firebase/Core', '4.0.0'

  target 'Goalish-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoalishTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
